version: '3.3'
services:

  db:
    # we use the mysql base image, version 5.6.36
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mdas
      POSTGRES_USER: postgres
      POSTGRES_DB: pythondb
    ports:
      - "5432:5432"
    networks:
      mynetwork:
        aliases:
          - web1.internal.prod.example.com
  web_backend:
    build:
      context: .
      dockerfile: ./infrastructure/docker/web_backend/Dockerfile
    user: root
    depends_on:
      - db
    links: 
      - "db:database"
    # volumes:
      # - ./backend:/var/www/html/
    # command: bash -c "/home/ec2-user/mdas_backend/boostrap.sh"
    ports:
      - "8050:8050"
    environment: []
    # command: php bin/cake.php
    # restart: unless-stopped
    networks:
      mynetwork:
        aliases:
          - web1.internal.prod.example.com
    # entrypoint: flask run
networks:
  mynetwork:
    driver: bridge