access_key = "AKIA6BN6VQCZBCLGGLW2"
secret_key = "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"
region = "us-east-2"
key_name = "mdas_key"
public_key_path = "keys/public_key"
private_key_path = "keys/private_key"